#!/bin/bash

. ./build-utils

echo 'Spawning new ec2 instance...'
EC2_HOST=`spawn-instance "matching-engine" 20 m1.xlarge`
[ $? != 0 ] && echo 'spawning ec2 instance failed' && exit 1

echo "Copying installation scripts to ${EC2_HOST}..."
scp -i ~/.ssh/gsmarquee.pem * .config root@${EC2_HOST}:/root/ >> /dev/null 2>&1

echo "Installing ${EC2_HOST}..."
ssh -i ~/.ssh/gsmarquee.pem root@${EC2_HOST}  './install-rt-kernel'
[ $? != 0 ] && echo 'installing ec2 instance failed' && exit 1

echo 'Build is done.'
